### ISSUE TITLE
Existing snapshots

### ISSUE THREAD

**Issue by kichik** [CloudSnorkel/cdk-rds-sanitized-snapshots#1]
Add an option to use the latest existing snapshot instead of taking a new one. Can be useful for big databases where snapshotting takes a long time and there is already an automated snapshot process like the system one.

**Comment by rmahnovetsky** [comment]
I agree. It specifies this in the documentation but I could not find the code for it or how to configure it.

1. Get a snapshot of the given database by either:
- Finding the latest snapshot for the given database
- Creating and waiting for a new fresh snapshot
