### ISSUE TITLE
State machine fail on RDS Serverless due to missing databaseInstance param

### ISSUE THREAD

**Issue by dannylinden** [CloudSnorkel/cdk-rds-sanitized-snapshots#53]
Hi, 

is this Construct compatible with RDS Serverless as source? Because the Step Function seems to fail due ti the missing `databaseInstance` as I only have the `databaseCluster` parameter for RDS Aurora Serverless?

If I only configure the `databaseCluster` parameter the Step Function shows the following error:

```
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'DBInstanceIdentifier' of undefined",
  "trace": [
    "TypeError: Cannot read property 'DBInstanceIdentifier' of undefined",
    "    at Runtime.exports.handler (/var/task/index.js:61:109)",
    "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  ]
}
```

**Comment by kichik** [comment]
Please reopen if you have further details.
