### ISSUE TITLE
Deprecating API

### ISSUE THREAD

**Issue by ricky-lim** [CloudSnorkel/cdk-rds-sanitized-snapshots#82]
[WARNING] aws-cdk-lib.aws_ec2.SubnetType#PRIVATE_WITH_NAT is deprecated.
  use `PRIVATE_WITH_EGRESS`
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_ec2.SubnetType#PRIVATE_WITH_NAT is deprecated.
  use `PRIVATE_WITH_EGRESS`
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_stepfunctions.StateMachineProps#definition is deprecated.
  use definitionBody: DefinitionBody.fromChainable()
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_stepfunctions.StateMachineProps#definition is deprecated.
  use definitionBody: DefinitionBody.fromChainable()
  This API will be removed in the next major release.

**Comment by kichik** [comment]
`SubnetType#PRIVATE_WITH_NAT` was deprecated with [PR #21699](https://github.com/aws/aws-cdk/pull/21699) and CDK [v2.41.0](https://github.com/aws/aws-cdk/releases/tag/v2.41.0). `StateMachineProps#definition` was deprecated with [PR #25932](https://github.com/aws/aws-cdk/pull/25932) and CDK [v2.85.0](https://github.com/aws/aws-cdk/releases/tag/v2.85.0).

We still support CDK v2.0.0. We can't stop using those until we stop supporting older versions of CDK v2.
